//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Procedura()
        {
            this.ServiciuProceduras = new HashSet<ServiciuProcedura>();
        }
    
        public int Id { get; set; }
        public string Denumire { get; set; }
        public int Pret { get; set; }
        public string Descriere { get; set; }
        public int Durata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiciuProcedura> ServiciuProceduras { get; set; }
    }
}
