//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Programare
    {
        public int ProgramareID { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Data { get; set; }
        public string PacientAnonim { get; set; }
        [Display(Name ="Pacient")]
        public string ApplicationUser_Id { get; set; }
        [Display(Name = "Doctor")]
        public string ApplicationUser1_Id { get; set; }
        public Nullable<int> ServiciuProcedura_ServiciuProceduraID { get; set; }
    
        public virtual ServiciuProcedura ServiciuProcedura { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
