//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta1
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class ServiciuProcedura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiciuProcedura()
        {
            this.Programares = new HashSet<Programare>();
        }
    
        public int ServiciuProceduraID { get; set; }
        public Nullable<int> Procedura_Id { get; set; }
        public Nullable<int> Serviciu_ServiciuID { get; set; }
    
        public virtual Procedura Procedura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programare> Programares { get; set; }
        public virtual Serviciu Serviciu { get; set; }

       
    }
}
