//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Testimonial
    {
        public int Id { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Data { get; set; }
        public string Descriere { get; set; }
        public bool Validat { get; set; }
        public string ApplicationUser_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
